### ISSUE TITLE
A wrong about MCinf-ranks

### ISSUE THREAD

**Issue by shenmadetoufa** [Bimmr/McInfected#100]
Hey , Bimmr :
I really like this game , but i have something wrong in Mcinf-rank , it doesn't work with the the latest version of Mcinf , do i need another front plugin ? :)
Here is the crash :
[17:00:26] [Server thread/INFO]: Using default channel type
[17:00:26] [Server thread/ERROR]: Could not load 'plugins\McInfected-Ranks.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: name '${name}' contains invalid characters.
at org.bukkit.plugin.PluginDescriptionFile.loadMap(PluginDescriptionFile.java:894) ~[spigot.jar:git-Spigot-044d928-e8c6403]
at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:232) ~[spigot.jar:git-Spigot-044d928-e8c6403]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[spigot.jar:git-Spigot-044d928-e8c6403]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-044d928-e8c6403]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-044d928-e8c6403]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-044d928-e8c6403]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-044d928-e8c6403]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[17:00:26] [Server thread/INFO]: Set PluginClassLoader as parallel capable

**Comment by Bimmr** [comment]
Hmmm, kinda odd that didn't change like the rest of the plugin.yml but I'll fix it. just gimmie a day.

**Comment by Bimmr** [comment]
Nvm, Just uploaded a version that should fix that issue.

**Comment by shenmadetoufa** [comment]
Thank you , very efficient
