### ISSUE TITLE
Translatable messages

### ISSUE THREAD

**Issue by Plajer** [Bimmr/McInfected#113]
Sorry if this wrong section to post propositions.

My proposition is to add new messages to be translatable.

Some of messages i can't translate:
"Return" message in Zombies and Humans kit selector:
https://scr.hu/LeygZL
"Random map" message in Voting GUI:
https://scr.hu/Ge4dY1
"Players needed" message on scoreboard:
https://scr.hu/gP0Yap
Sign messages:
https://scr.hu/ymZD9r
Stats when sneaking in lobby:
https://scr.hu/ymZD9r

You can add this messages in next update :p.

**Comment by Plajer** [comment]
Some errors:
[code]
 [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.4.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:847) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:826) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1585) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Team name '§6§r§r' is already in use
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:140) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at me.bimmr.bimmcore.scoreboard.BoardLine.setBoard(BoardLine.java:89) ~[?:?]
	at me.bimmr.bimmcore.scoreboard.Board.add(Board.java:179) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:207) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:339) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:310) ~[?:?]
	at com.bimmr.mcinfected.IPlayers.IPlayer.infect(IPlayer.java:568) ~[?:?]
	at com.bimmr.mcinfected.IPlayers.IPlayer.die(IPlayer.java:146) ~[?:?]
	at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:169) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 26 more

and

[18:12:10] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to McInfected v1.4.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerList.disconnect(PlayerList.java:385) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1068) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.NetworkManager.handleDisconnection(NetworkManager.java:318) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:174) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:827) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Team name '§6§r§r' is already in use
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:140) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at me.bimmr.bimmcore.scoreboard.BoardLine.setBoard(BoardLine.java:89) ~[?:?]
	at me.bimmr.bimmcore.scoreboard.Board.add(Board.java:179) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:207) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:339) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:310) ~[?:?]
	at com.bimmr.mcinfected.IPlayers.IPlayer.leave(IPlayer.java:703) ~[?:?]
	at com.bimmr.mcinfected.Command.LeaveCommand.leave(LeaveCommand.java:20) ~[?:?]
	at com.bimmr.mcinfected.Listeners.MiscListeners.onPlayerLeave(MiscListeners.java:158) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 12 more
[/code]

**Comment by Bimmr** [comment]
Thanks for the error, but please make a new ticket, and explain what you did that caused this error. Because if I just handed you a piece of paper with part of a story on it you wouldn't have the context that the story is about. So that's how I feel about just seeing an error and not having any details about it.

**Comment by Plajer** [comment]
Okay ;)
I wanna apologize. I downgraded server to 1.8 for some problems with guns. Now this errors don't appear.
I'll post new tickets when another errors will appear.
