### ISSUE TITLE
not compatible with 1.11.2

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#114]
when any titles are displayed, clients crash with a json error: https://gyazo.com/a05ba4745ef581aecd9a291d716225d0

a second error, when infected win there is another client crash with the same json error, as well as this in console

```
[13:12:46] [Server thread/INFO]: PhanaticD has died
[13:12:46] [Server thread/INFO]: PhanaticD has been infected
[13:12:46] [Server thread/INFO]: PhanaticD Equiped with Infected's Zombie
[13:12:46] [Server thread/INFO]: ZOMBIE
[13:12:46] [Server thread/INFO]: legit_craft has gotten a kill
[13:12:46] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.4.3
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1019]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1019]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1019]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1019]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1019]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:91) [patched_1.11.2.jar:git-Paper-1019]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:576) [patched_1.11.2.jar:git-Paper-1019]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:481) [patched_1.11.2.jar:git-Paper-1019]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:608) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1329) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:871) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:527) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1030) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1199) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1607) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-1019]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1019]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1019]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: org.bukkit.configuration.MemorySection cannot be cast to java.util.List
    at com.bimmr.mcinfected.SettingsManager.getRewards(SettingsManager.java:429) ~[?:?]
    at com.bimmr.mcinfected.IPlayers.IPlayer.win(IPlayer.java:908) ~[?:?]
    at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:188) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor393.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1019]
    ... 27 more
[13:12:46] [Server thread/INFO]: PhanaticD has been healed
[13:12:46] [Server thread/INFO]: legit_craft lost connection: Disconnected
[13:12:46] [Server thread/INFO]: Using Table: McInfected; Setting  2c2a05d9-6f3e-4d8b-9bf8-1ac6805ff065 - Exp
[13:12:46] [Server thread/INFO]: Using Table: McInfected; Setting  2c2a05d9-6f3e-4d8b-9bf8-1ac6805ff065 - Rank
[13:12:46] [Server thread/INFO]: legit_craft has left
```

**Comment by Bimmr** [comment]
I'm actually just looking at this now. There were apparently a handful of things that changed in 1.11

**Comment by Bimmr** [comment]
Are you able to send me your config.yml?

**Comment by PhanaticD** [comment]
http://pastebin.com/raw/Ux3HPrAS

**Comment by Bimmr** [comment]
The error is caused because you tried removing rewards in a way that doesn't work.

>  Rewards:
>     Enable: false

What you'll actually want is
```
  Rewards: []
```

**Comment by PhanaticD** [comment]
ok

**Comment by Bimmr** [comment]
Both issues are fixed so...

**Comment by PhanaticD** [comment]
thanks!
