### ISSUE TITLE
API Suggestions

### ISSUE THREAD

**Issue by Maxetto** [Bimmr/McInfected#118]
Trying to use the API, I found some lack of features and a Bug:
- Inability to set the IKiller and get Damage and DamageCause in McInfectedDeathEvent (Maybe wrap the EntityDamageByEntityEvent?)
- Inability to get and set the Kit on McInfectedEquipEvent (e.getIPlayer().getHumanKit() saves changes to the file, which is something I don't want), the event should contain the IPlayer that is being equipped and the Kit that is about to be given to him, in order to do something with that without saving it in the file)
- McInfectedEquipEvent is called twice when joining the game (**Bug!**)
- McInfectedInfectEvent prints the Infected message even when Cancelled (this is because the .sendMessage() is handled by McInfectedDeathEvent) (**Bug!**)
- McInfectedLeaveEvent prints the "you cannot leave the game" even if the event is uncancelled (I have this because I don't want anyone to be OP but still allow Staff with a custom permission to leave the game, while they usually can't due to McInfected-Dedicated).
- Inability to get and set the Spawn Point and the Map the user is being respawned to on McInfectedRespawnEvent
- Missing McInfectedSpawnEvent (or maybe it calls McInfectedRespawnEvent even in the 1st spawn... Didn't test)

**Comment by Maxetto** [comment]
Progress about McInfectedInfectEvent, I've managed to add lives with p.setLives(2), but the message about being Killed is shown anyway.

**Comment by Bimmr** [comment]
These probably won't be in the next update but I will make sure they are in
the following one, the API is something I do need to fix up and I'm
actually able to work on McInfected currently.

**Comment by Maxetto** [comment]
I have no hurry for them, but if you find some time and you're able to sneak in the "McInfectedEquipEvent" suggestion in the next update, I would be more than happy. :D

**Comment by Bimmr** [comment]
So I fixed it so that setting on the kit won't save to the file, but as for making events return a few more things that'll have to be in the following update. So you'll have to use `event.getIPlayer().getKit(event.getIPlayer().getTeam());`
for now.

**Comment by Bimmr** [comment]
Instead of the McInfectedInfectEvent try using McInfectedDeathEvent. A quick glance at the code is making me think I never actually implemented Infect event.

**Comment by Bimmr** [comment]
Also, for McInfectedLeaveEvent you may have to set a high event priority. McInfected-Dedicated is on normal and in the new version I have changed it lowest.

**Comment by Maxetto** [comment]
Will try setting higher priority, even if I recall to already have tried that...

McInfectedInfectEvent is actually implemented and called after McInfectedDeathEvent, if the user is a Human and has run out of lives (McInfectedDeathEvent doesn't call McInfectedInfectEvent until out of lives). Cancelling McInfectedDeathEvent makes the player die as a normal user and so this is not convenient for just removing a sendMessage line. I found it's better to cancel the McInfectedInfectEvent, respawn the user and broadcast that he's respawned.

McInfectedRespawnEvent -> Great ;)


Other things I found, McInfectedEquipEvent is called twice when joining the game, both in the same gamestate and for the same team (as I thought it might be called when in Team.Global and in Team.\<the_team_you_joined\>).

**Comment by Maxetto** [comment]
I actually found a Bug in your CrackShot implementation:
With No Damage Grenades, if the victim has less health than the damage the grenade is supposed to do (Because there's no way to get if it's a tactical grenade, etc.) the victim dies.
No matter the priority of the event. I tried setting damage to 0.0 and/or cancelling the event on "WeaponDamageEntityEvent" (Priority HIGHEST) but it didn't work (I found you also don't ignore cancelled events).
I tried than to set EntityDamageEvent and EntityDamageByEntityEvent to 0.0 damage and/or cancelling it if the damage cause was ENTITY_EXPLOSION (as it seems Crackshot calls an EntityDamageEvent as PlayerAttack after the original ENTITY_EXPLOSION, so it should be safe to cancel it), but it didn't work again.

I might try getting the DamageCause of McInfectedDeathEvent and try to work with that but I think this might not work too.


Also, there's an error when you kill someone with Crackshot:
```
[10:29:04] [Server thread/ERROR]: Could not pass event WeaponDamageEntityEvent to McInfected v1.4.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at com.shampaggon.crackshot.CSDirector.onDamage(CSDirector.java:1067) [CrackShot.jar:?]
	at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:445) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.Explosion.a(Explosion.java:131) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.createExplosion(World.java:1866) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.createExplosion(WorldServer.java:1020) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:84) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityTNTPrimed.t_(EntityTNTPrimed.java:63) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at com.bimmr.mcinfected.Kits.Kit.checkKillStreak(Kit.java:167) ~[?:?]
	at com.bimmr.mcinfected.IPlayers.IPlayer.kill(IPlayer.java:624) ~[?:?]
	at com.bimmr.mcinfected.Listeners.CrackShotEvents.onPlayerDamage(CrackShotEvents.java:59) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor273.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	... 33 more
```

**Comment by Maxetto** [comment]
Could you please make a changelog of what you changed (API-wise) in the latest Dev version?

Thank you.

**Comment by Bimmr** [comment]
- All damage events in McInfected now check if the event was canceled before doing anything
- McInfected addons now listen to McInfected events on the Lowest priority
- Kit/Lobby set functions will no longer apply changes to appropriate YAML files

Those are the ones I can remember. I will be doing next:
- McInfectedDeathEvent will also have the DamageEvent
- McInfectedEquipEvent will have the kit that is being equipped

**Comment by Bimmr** [comment]
I was just testing for 

> McInfectedEquipEvent is called twice when joining the game (Bug!)

and I'm not able to replicate it. Did I perhaps already fix it?

**Comment by Maxetto** [comment]
Will try soon. It might be. I was using that event to workaround the inventory setting, but since now it's inside the event it might have been blindly fixed (or at least not needed anymore).

**Comment by Bimmr** [comment]
Oh also if it helps; Kits support a list of items under the key "Extra", for example:
  ```
Private:
      Icon: item:SKULL_ITEM data:3
      Inventory:
      - item:STONE_SWORD
      Extra:
      - ZombieHealer
      - GoldenApple glow name:Apple_Of_Zoom potion:1,10,1
      Armor:
        Helmet: item:LEATHER_HELMET color:237,55,167
        Chestplate: item:LEATHER_CHESTPLATE color:237,55,167
        Leggings: item:LEATHER_LEGGINGS color:237,55,167
        Boots: item:LEATHER_BOOTS color:237,55,167
      Description:
      - '&3- Stone Sword'
      - '&7- Leather Helmet'
      - '&7- Leather Chestplate'
      - '&7- Leather Leggings'
      - '&7- Leather Boots'
      KillStreaks:
        '8': gun:Airstrike
```

Then the kit will have everything loaded in kit.getExtras(), the only thing is that if you set to the extras it won't be saved to the config.

**Comment by Bimmr** [comment]
Just giving you a heads up. The next version of McInfected is going to change a good portion of the API to try and make it a little more friendly. Once I have more information on what I'm changing I'll let you know.
