### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to McInfected v1.4.4

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#119]
```
[20:12:03 ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.4.4
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1032]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:91) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:576) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:481) [patched_1.11.2.jar:git-Paper-1032]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:608) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1329) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:871) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:528) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1030) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1203) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1608) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-1032]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1032]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1032]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at me.bimmr.bimmcore.scoreboard.BoardLine.build(BoardLine.java:167) ~[?:?]
        at me.bimmr.bimmcore.scoreboard.BoardLine.setText(BoardLine.java:112) ~[?:?]
        at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:214) ~[?:?]
        at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:341) ~[?:?]
        at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:312) ~[?:?]
        at com.bimmr.mcinfected.IPlayers.IPlayer.infect(IPlayer.java:568) ~[?:?]
        at com.bimmr.mcinfected.IPlayers.IPlayer.die(IPlayer.java:143) ~[?:?]
        at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:174) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor401.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1032]
        ... 27 more
```

**Comment by Bimmr** [comment]
Odd, to be perfectly honest. I'm not to sure why this error is happening. It's saying that something is null(nothing) but if it's nothing then the code shouldn't even know about it and try to use it... I'll have to play around with it a bit.

**Comment by Bimmr** [comment]
I'll be uploading a version later tonight that **might** fix this issue. Because I'm not able to get 16+ people on a test server this scoreboard bug is a little difficult to debug.
