### ISSUE TITLE
McInfected errors

### ISSUE THREAD

**Issue by Plajer** [Bimmr/McInfected#129]
**Version:** 1.8.7 paperspigot
**List of errors:**
- [ ] 1. Ingame Transfer Potions editor error

**1. Ingame Transfer Potions editor**
**Errors:**
```Plajer issued server command: /McInfected Setup Kit Ninja TransferEffects
[15:29:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mcinfected' in plugin McInfected v1.4.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1166) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_111]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_111]
        at com.bimmr.mcinfected.Command.Setup.KitSetup.run(KitSetup.java:206) ~[?:?]
        at com.bimmr.mcinfected.Command.SetupCommand.execute(SetupCommand.java:100) ~[?:?]
        at me.bimmr.bimmcore.commands.CommandHandler.onCommand(CommandHandler.java:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
        ... 15 more
```
**Part of config:**
```
    Transfer Potions:
    - type:2 duration:1 amplifier:1
    - type:2 duration:1 amplifier:1
```
(here it works)
**More info:**
Gif (video) here http://imgur.com/a/vE115

**Comment by Bimmr** [comment]
I'll have to look at this when I get a chance. Have a list of projects I need to work on first.

**Comment by Bimmr** [comment]
Just wanted to post an update so it doesn't look like I forgot about this. I believe I have this fixed, but I will have to double check it tomorrow.
