### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#130]
```
[10:46:23] [Server thread/ERROR]: Could not pass event EntityDamageEvent to McInfected v1.4.4
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1055]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:91) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:576) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:562) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:608) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1329) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:871) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:528) ~[patched_1.11.2.jar:git-Paper-1055]
    at fr.neatmonster.nocheatplus.compat.cbdev.MCAccessCBDev.dealFallDamage(MCAccessCBDev.java:235) ~[?:?]
    at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.dealFallDamage(NoFall.java:133) ~[?:?]
    at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.handleOnGround(NoFall.java:87) ~[?:?]
    at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.check(NoFall.java:229) ~[?:?]
    at fr.neatmonster.nocheatplus.checks.moving.MovingListener.checkPlayerMove(MovingListener.java:800) ~[?:?]
    at fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMove(MovingListener.java:486) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor296.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1055]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.11.2.jar:git-Paper-1055]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:617) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1055]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1055]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1055]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at com.bimmr.mcinfected.Listeners.EntityDamage.onEntityDamage(EntityDamage.java:77) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor405.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1055]
    ... 37 more
```

**Comment by Bimmr** [comment]
I've re-coded the whole way McInfected manages damage, so I'm hoping that will fix this and crackshot issues
