### ISSUE TITLE
Rank Issues

### ISSUE THREAD

**Issue by zvvx** [Bimmr/McInfected#132]
Whenever I click on the button Create Rank in the chat menu it errors and it outputs

[18:00:30 INFO]: zvvx issued server command: /McInfected setupnf Rank CreateRank
[18:00:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mcinfected' in plugin McInfected v1.4.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-65a0347-1a71021]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-65a0347-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-65a0347-1a71021]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-65a0347-1a71021]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at com.bimmr.mcinfectedranks.Commands.Setup.SetupRanks.run(SetupRanks.java:164) ~[?:?]
        at com.bimmr.mcinfected.Command.SetupCommand.execute(SetupCommand.java:100) ~[?:?]
        at me.bimmr.bimmcore.commands.CommandHandler.onCommand(CommandHandler.java:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-65a0347-1a71021]
        ... 15 more

**Comment by zvvx** [comment]
Also the permissions seem to have no affect on what players can choose for their lobby or kit

**Comment by Bimmr** [comment]
What version of McInfected & McInfected Ranks are you using?

**Comment by zvvx** [comment]
Using 1.4.4 for McInfected and 1.2.1 for Ranks

**Comment by zvvx** [comment]
And for the permissions am I correct that you can either do - -McInfected.Kits.* and do -McInfected.Kits.<kitname> to give permission for certain kits OR do - -McInfected.Kits.<kitname> for each kit you DO NOT want a player to use.

**Comment by Bimmr** [comment]
It depends on your permissions plugin. Not all plugins will accept `-<permission>` as negating. You're best bet is to disable allowing all perms, then give the players perms to the proper groups manually.

**Comment by zvvx** [comment]
I'm currently testing just McInfected Ranks for the only permission plugin so how would it work?

**Comment by Bimmr** [comment]
McInfected-Ranks isn't a permissions plugin. You'll still need one on your server. All it does it add the permissions to your permissions plugin.

**Comment by zvvx** [comment]
I'm trying to understand what you mean. What permissions are supposed to go into the Ranks.yml file?

**Comment by zvvx** [comment]
Ok, all I'm asking is how do I set it up so when a player ranks up they can unlock more kits.

**Comment by zvvx** [comment]
"Another thing you can do is give Ranks special permissions. Any permissions given to the rank are only given to the player while they are in McInfected. Once they leave mcinfected, any permissions they may have been given will be removed. Although this does require Vault to be on the server." OH YOU NEED VAULT. Completely forgot about that sorry
