### ISSUE TITLE
iDisiguise error

### ISSUE THREAD

**Issue by Blackyvk** [Bimmr/McInfected#136]
I got this after updating to the lastest version available.

I'm using iDisguise 5.6.1
Spigot 1.11.2

```
[McInfected] Task #4717 for McInfected v1.4.4 generated an exception
java.lang.NoSuchMethodError: de.robingrether.idisguise.disguise.MobDisguise.<init>(Lde/robingrether/idisguise/disguise/DisguiseType;Z)V
	at com.bimmr.mcinfected.Disguises.IDisguise.disguise(IDisguise.java:41) ~[?:?]
	at com.bimmr.mcinfected.Disguises.DisguiseManager.disguise(DisguiseManager.java:62) ~[?:?]
	at com.bimmr.mcinfected.IPlayers.IPlayer.disguise(IPlayer.java:156) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.Timers$3.run(Timers.java:373) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by Bimmr** [comment]
For now just use an older version of iDisguise as there isn't going to be
any fixes till closer to the end of the month. Final exams are coming up.

**Comment by Bimmr** [comment]
I've updated my build to use iDisguise 5.6.2 and so far everything seems to work right

**Comment by Blackyvk** [comment]
Thanks!
