### ISSUE TITLE
(dev version) NPE EntityDamage

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#139]
```
[09:16:16] [Server thread/ERROR]: Could not pass event EntityDamageByBlockEvent to McInfected v1.4.5
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1081]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1081]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1081]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1081]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1081]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [patched_1.11.2.jar:git-Paper-1081]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:491) [patched_1.11.2.jar:git-Paper-1081]
    at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:610) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1330) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:872) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:530) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.Entity.burnFromLava(Entity.java:504) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.Entity.U(Entity.java:457) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityLiving.U(EntityLiving.java:198) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.Entity.A_(Entity.java:330) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1844) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityHuman.A_(EntityHuman.java:143) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.EntityPlayer.playerTick(EntityPlayer.java:288) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.PlayerConnection.F_(PlayerConnection.java:139) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1081]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1081]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
    at com.bimmr.mcinfected.Listeners.EntityDamage.onDamage(EntityDamage.java:174) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor461.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1081]
    ... 27 more
```

**Comment by Bimmr** [comment]
I think I've fixed this, going to test it tomorrow to make sure. Just wanted to give an update so you didn't think I forgot about it.
