### ISSUE TITLE
Errors on startup or "/infected setup"

### ISSUE THREAD

**Issue by jsslcy** [Bimmr/McInfected#142]
## What's Currently Happening
Errors on startup or "/infected setup"

----
## Steps to Reproduce (for bugs)
Errors on server startup
or
/infected setup
----
## Error Code
```
[19:56:31] [Server thread/INFO]: Loaded Human Kit: Captain
[19:56:31] [Server thread/INFO]: Loaded Human Kit: General
[19:56:31] [Server thread/INFO]: Loaded Infected Kit: Zombie
[19:56:31] [Server thread/INFO]: Loaded Infected Kit: Skeleton
[19:56:31] [Server thread/INFO]: Loaded Infected Kit: Witch
[19:56:31] [Server thread/INFO]: For Disguise Support we're using LibsDisguise
[19:56:31] [Server thread/INFO]: Filling Disguises.yml with possible disguises for LibsDisguises
[19:56:31] [Server thread/ERROR]: Error occurred while enabling McInfected v1.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/bimmr/bimmcore/events/message/FancyClickEvent
at com.bimmr.mcinfected.Command.BSetupCommand.<init>(BSetupCommand.java:38) ~[?:?]
at com.bimmr.mcinfected.McInfected.setupCommandHandler(McInfected.java:386) ~[?:?]
at com.bimmr.mcinfected.McInfected.onEnable(McInfected.java:273) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: me.bimmr.bimmcore.events.message.FancyClickEvent
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
... 14 more
[19:56:31] [Server thread/INFO]: [McInfectedLobbyItems] Enabling McInfectedLobbyItems v0.1.0
[19:56:31] [Server thread/ERROR]: [McInfectedLobbyItems] Plugin McInfectedLobbyItems v0.1.0 has failed to register events for class com.bimmr.mcinfectedlobbyitems.Listeners because com/bimmr/mcinfected/Events/McInfectedTimerEvent does not exist.
[19:56:31] [Server thread/INFO]: [McInfectedRanks] Enabling McInfectedRanks v1.2.2
[19:56:31] [Server thread/ERROR]: Error occurred while enabling McInfectedRanks v1.2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: me/bimmr/bimmcore/events/message/FancyClickEvent
at com.bimmr.mcinfectedranks.McInfectedRanks.onEnable(McInfectedRanks.java:216) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: me.bimmr.bimmcore.events.message.FancyClickEvent
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
... 12 more
[19:56:31] [Server thread/INFO]: [McInfectedDedicated] Enabling McInfectedDedicated v0.1.7
```

----
## Your Environment
* Spigot Version used:  1.8.8
* McInfected Version: newest
* BimmCore Version: newest
* Any Addons?(Include their versions)

**Comment by Bimmr** [comment]
Saying that the version is newest is 100% useless, as it is not the newest, the newest is 0.0.8 which I forgot to upload.(Which is the issue). 

When you say newest it could mean anything. Newest in the dev folder, newest as of a week ago, newest as of 24 hours ago.

**Comment by jsslcy** [comment]
Damn didn't mean to piss you off, but you're right.  I should have filled out this information.  

I used the new version of BimmCore (v0.0.8) and still getting errors:
[https://hastebin.com/nonetilaza.md](https://hastebin.com/nonetilaza.md)

**Comment by Bimmr** [comment]
Looks like BimmCore didn't build right. Gimmie a minute to fix and upload.

**Comment by jsslcy** [comment]
Not taking input for lobby name.

![2017-05-31_15 22 48](https://cloud.githubusercontent.com/assets/28246801/26660677/377ca2e2-4615-11e7-96d7-f491e7a60f3a.png)

**Comment by Bimmr** [comment]
Looking at that screenshot it looks like there was an error loading the
Messages.yml as well. Did it create the file? Was there any other errors in
the console when the server started?

**Comment by jsslcy** [comment]
It was a new server, somehow the full Messages.yml wasn't created, but I moved the Messages.yml from another server and setup is working correctly.

However, there are some issues still on server startup

[11:07:26] [Server thread/INFO]: [McInfected] Connecting to MySQL Database
[11:07:26] [Server thread/ERROR]: Error occurred while enabling McInfected v1.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
at me.bimmr.bimmcore.mysql.MySQLManager.<init>(MySQLManager.java:22) ~[?:?]
at com.bimmr.mcinfected.McInfected.onEnable(McInfected.java:305) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
... 13 more
[11:07:26] [Server thread/INFO]: [McInfectedLobbyItems] Enabling McInfectedLobbyItems v0.1.0
[11:07:26] [Server thread/ERROR]: [McInfectedLobbyItems] Plugin McInfectedLobbyItems v0.1.0 has failed to register events for class com.bimmr.mcinfectedlobbyitems.Listeners because com/bimmr/mcinfected/Events/McInfectedJoinEvent does not exist.
[11:07:27] [Server thread/INFO]: [McInfectedRanks] Enabling McInfectedRanks v1.2.2
[11:07:27] [Server thread/ERROR]: Error occurred while enabling McInfectedRanks v1.2.2 (Is it up to date?)
java.lang.NullPointerException
at com.bimmr.mcinfectedranks.McInfectedRanks.onEnable(McInfectedRanks.java:197) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[11:07:27] [Server thread/INFO]: [McInfectedDedicated] Enabling McInfectedDedicated v0.1.7

**Comment by Bimmr** [comment]
Moving computers caused issues with my files apparently it should all be working now, I gave it a quick test on a fresh server.

**Comment by jsslcy** [comment]
LOL, Sorry but still throwing errors.


[15:48:44] [Server thread/INFO]: [McInfected] Connecting to MySQL Database
[15:48:44] [Server thread/ERROR]: Error occurred while enabling McInfected v1.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
at me.bimmr.bimmcore.mysql.MySQLManager.<init>(MySQLManager.java:22) ~[?:?]
at com.bimmr.mcinfected.McInfected.onEnable(McInfected.java:306) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
... 13 more
[15:48:45] [Server thread/INFO]: [McInfectedLobbyItems] Enabling McInfectedLobbyItems v0.1.0
[15:48:45] [Server thread/ERROR]: [McInfectedLobbyItems] Plugin McInfectedLobbyItems v0.1.0 has failed to register events for class com.bimmr.mcinfectedlobbyitems.Listeners because com/bimmr/mcinfected/Events/McInfectedTimerEvent does not exist.
[15:48:45] [Server thread/INFO]: [McInfectedRanks] Enabling McInfectedRanks v1.2.2
[15:48:45] [Server thread/ERROR]: Error occurred while enabling McInfectedRanks v1.2.2 (Is it up to date?)
java.lang.NullPointerException
at com.bimmr.mcinfectedranks.McInfectedRanks.onEnable(McInfectedRanks.java:197) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[15:48:45] [Server thread/INFO]: [McInfectedDedicated] Enabling McInfectedDedicated v0.1.7

**Comment by Bimmr** [comment]
Did you also grab the update for BimmCore?

**Comment by jsslcy** [comment]
I did. Both were updated today.

**Comment by Bimmr** [comment]
Damn, It'll be a bit before I'm going to be able to try and troubleshoot
MySQL Support

**Comment by jsslcy** [comment]
I can setup FTP access and give you OP, if you would like to test things out.

Just let me know.

**Comment by Bimmr** [comment]
Uploaded what should fix it(BimmCore update), tested on my computer and it seemed to work this time.

**Comment by Bimmr** [comment]
Fixed
