### ISSUE TITLE
leaderheads couldn't load mcinfected leaderheads

### ISSUE THREAD

**Issue by eric2788** [Bimmr/McInfected#143]
## What's Currently Happening

title say it all

----
## Steps to Reproduce (for bugs)

1.  full log: https://pastebin.com/u247mKjQ
2. my leaderheads version = 3.0.1
----
## Error Code
```
[15:11:44 INFO]: [LeaderHeads] Statistic is not in list, adding it: McInf-Kills
	at com.bimmr.mcinfectedleaderboards.Api.LeaderHeads.McInfectedLeaderHeadsStats.<init>(McInfectedLeaderHeadsStats.java:15) ~[?:?]
	at com.bimmr.mcinfectedleaderboards.Api.LeaderHeads.LeaderHeadsAPI.setup(LeaderHeadsAPI.java:26) ~[?:?]
	at com.bimmr.mcinfectedleaderboards.McInfectedLeaderboards.onEnable(McInfectedLeaderboards.java:44) ~[?:?]
eaderheads.datacollectors.DataCollector.<init>(DataCollector.java:10) ~[?:?]
	at me.robin.leaderheads.datacollectors.OnlineDataCollector.<init>(OnlineDataCollector.java:12) ~[?:?]
	at com.bimmr.mcinfectedleaderboards.Api.LeaderHeads.McInfectedLeaderHeadsStats$McInfectedKills.<init>(McInfectedLeaderHeadsStats.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[server.jar:git-Paper-1101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [server.jar:git-Paper-1101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [server.jar:git-Paper-1101]
	at org.bukkit.craf	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[server.jar:git-Paper-1101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [server.jar:git-Paper-1101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [server.jar:git-Paper-1101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [server.jar:git-Paper-1101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [server.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [server.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [server.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [server.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [server.jar:git-Paper-1101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [server.jar:git-Paper-1101]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[15:11:44 INFO]: [McInfectedLeaderboards] Disabling McInfectedLeaderboards v0.1.1


----
## Your Environment
* Spigot Version used: 1.11.2
* McInfected Version: 1.5.0
* BimmCore Version: 0.0.8
* Any Addons?(Include their versions, and DO NOT say newest
ranks[v1.2.2]

**Comment by Bimmr** [comment]
Right now his website that has the documentation for leaderboards API is
down, so once it comes back up i'll look into it

**Comment by Bimmr** [comment]
![image](https://user-images.githubusercontent.com/5053870/27448571-36e8cc26-5753-11e7-884f-330146eac711.png)
Websites still down for me so I can't look into his API to fix it.

**Comment by Bimmr** [comment]
Would you be able to test Leaderheads support? Without the plugin it's a little difficult to test.

**Comment by eric2788** [comment]
ok, could you tell me how to test it?

**Comment by Bimmr** [comment]
You'd just throw the jar onto your that has McInfected & LeaderHeads, then try and see if it works. If it doesn't then report the error back to me.

**Comment by eric2788** [comment]
how could i get your fixed version?

**Comment by Bimmr** [comment]
I can send you the link over Spigot, just send me a message and I'll send you the link

**Comment by eric2788** [comment]
this happened again on the latest version of leaderheads

https://pastebin.com/VeDi68W8
