### ISSUE TITLE
McInfected Leaderboard is having error while enabling the plugin

### ISSUE THREAD

**Issue by eric2788** [Bimmr/McInfected#163]
McInfected Leaderboard is having error while enabling the plugin
## What's Currently Happening

I have installed the lastest version of McInfected and the latest version of Mcinfected leaderboard
----
## Steps to Reproduce (for bugs)

1. Installed the plugin

2. Open the server

3. The error appeared while enabling the plugin

----
## Error Code
```
[McInfectedLeaderboards] Enabling McInfectedLeaderboards v0.1.2
[10:26:48] [Server thread/INFO]: LeaderHeads has been found on the server. Using LeaderHeads Leaderboards instead.
[10:26:48] [Server thread/ERROR]: Error occurred while enabling McInfectedLeaderboards v0.1.2 (Is it up to date?)
java.lang.NullPointerException: null
    at me.robin.leaderheads.datacollectors.cv.<init>(cv.java:98) ~[?:?]
    at me.robin.leaderheads.datacollectors.DataCollector.<init>(DataCollector.java:6) ~[?:?]
    at com.bimmr.mcinfectedleaderboards.Api.LeaderHeads.McInfectedLeaderHeadsStats$McInfectedKills.<init>(McInfectedLeaderHeadsStats.java:36) ~[?:?]
    at com.bimmr.mcinfectedleaderboards.Api.LeaderHeads.McInfectedLeaderHeadsStats.<init>(McInfectedLeaderHeadsStats.java:23) ~[?:?]
    at com.bimmr.mcinfectedleaderboards.Api.LeaderHeads.LeaderHeadsAPI.setup(LeaderHeadsAPI.java:26) ~[?:?]
    at com.bimmr.mcinfectedleaderboards.McInfectedLeaderboards.onEnable(McInfectedLeaderboards.java:44) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Paper-1344]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [server.jar:git-Paper-1344]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Paper-1344]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [server.jar:git-Paper-1344]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [server.jar:git-Paper-1344]
    at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [server.jar:git-Paper-1344]
    at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [server.jar:git-Paper-1344]
    at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [server.jar:git-Paper-1344]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [server.jar:git-Paper-1344]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-Paper-1344]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[10:26:48] [Server thread/INFO]: [McInfectedLeaderboards] Disabling McInfectedLeaderboards v0.1.2<!--- Please put the error in between the ``` tags -->  

```

----
## Your Environment

* Spigot Version used: 1.12.2 the latest
* McInfected Version: 1.5.2
* BimmCore Version: 0.0.8
* Any Addons?(Include their versions)
McInfected dedicated 0.1.7
McInfected Ranks 1.2.4
McInfected LobbyItems 1.0.0
McInfected leaderboards 0.1.2 (You have sent me the version which can support leaderheads before)
//
LeaderHeads 3.1.6

**Comment by Bimmr** [comment]
I'll take a look when I get time, right now college is keeping me busy

**Comment by eric2788** [comment]
successfully enabled now, but i got an error while putting signs
`> [15:19:16 ERROR]: [LeaderHeads] Error while updating the mcinf-kills statistic
java.lang.NullPointerException: null
at com.bimmr.mcinfectedleaderboards.Api.LeaderHeads.McInfectedLeaderHeadsStats$McInfectedKills.requestAll(McInfectedLeaderHeadsStats.java:43) ~[McInfected-Leaderboards.jar:?]
at me.robin.leaderheads.datacollectors.cm.i(cm.java:21) [LeaderHeads.jar:?]
at me.robin.leaderheads.datacollectors.co.run(co.java:2) [LeaderHeads.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1371]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1371]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1371]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]`

**Comment by Bimmr** [comment]
I finally have free time. If you have free time to do some testing some day, send a message. Without having purchased the leaderboards plugin myself it is a little tricky to troubleshoot.

**Comment by eric2788** [comment]
do you have discord ? i think there should be a better communication side

**Comment by Bimmr** [comment]
As of a few minutes ago, https://discord.gg/6rxefEv
