### ISSUE TITLE
McInfected: Command Error

### ISSUE THREAD

**Issue by rosethenoob** [Bimmr/McInfected#164]
## What's Currently Happening
I am getting an error where when I put the command in chat, it just repeats it back to me.
----
## Steps to Reproduce (for bugs)
1. All you need to do is just put the command in chat.
----
## Error Code
No Errors pop up in my console...

----
## Your Environment

* Spigot Version used: CraftBukkit version git-Spigot-59b08be-0899683 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
* McInfected Version: 1.5.2
* BimmCore Version: 0.0.8
* Any Addons? iDisguise 5.6.4

**Comment by Bimmr** [comment]
If it's just repeating the command back, there should be an error when the
server is loading

**Comment by rosethenoob** [comment]
@Bimmr I'm sorry about that, I didn't know. Heres the error code... Also I forgot to mention that I am using CrackShot v0.98.7

[19:52:06] [Server thread/INFO]: [McInfected] Enabling McInfected v1.5.2
[19:52:06] [Server thread/INFO]: -----=========[[ McInfected ]]=========-----[m
[19:52:06] [Server thread/INFO]: Loaded Human Kit: Private[m
[19:52:06] [Server thread/INFO]: Loaded Human Kit: Captain[m
[19:52:06] [Server thread/INFO]: Loaded Human Kit: General[m
[19:52:06] [Server thread/INFO]: Loaded Infected Kit: Zombie[m
[19:52:06] [Server thread/INFO]: Loaded Infected Kit: Skeleton[m
[19:52:06] [Server thread/ERROR]: Error occurred while enabling McInfected v1.5.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
at me.bimmr.bimmcore.items.Items.fromString(Items.java:296) ~[?:?]
at me.bimmr.bimmcore.items.Items.(Items.java:46) ~[?:?]
at com.bimmr.mcinfected.Kits.Kit.(Kit.java:65) ~[?:?]
at com.bimmr.mcinfected.Kits.KitManager.createKit(KitManager.java:33) ~[?:?]
at com.bimmr.mcinfected.Kits.KitManager.loadKitsFromFile(KitManager.java:119) ~[?:?]
at com.bimmr.mcinfected.Kits.KitManager.(KitManager.java:23) ~[?:?]
at com.bimmr.mcinfected.McInfected.reload(McInfected.java:172) ~[?:?]
at com.bimmr.mcinfected.McInfected.onEnable(McInfected.java:271) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemFlag
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigotmc-1.8-R0.1.jar:git-Spigot-59b08be-0899683]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
... 19 more

**Comment by Bimmr** [comment]
If you don't mind me asking, why are you using 1.8.0 instead of a newer
version like 1.8.8? (Side note, I think 1.8.1 would probably fix the issue
that's causing the crash, can confirm in a bit)

**Comment by rosethenoob** [comment]
Ah, because im like a specific freak, and this one plugin was in 1.8 and so, i'm just like, "Welp! Better switch to 1.8." Thanks for the help, and great plugin :D
