### ISSUE TITLE
1.13.2 Update Request

### ISSUE THREAD

**Issue by LadyHaley** [Bimmr/McInfected#169]
I love this funky little update, I was hoping there would be an update on the way some time soon, especially considering 1.14 is around the corner, from the sounds of it, it should be easier to upgrade from 1.13 to 1.14

**Comment by Bimmr** [comment]
I suppose I could look into updating. Although is there anything in particular that isn't working on the newer versions?

**Comment by TKwSni** [comment]
this for example
```
[Server thread/ERROR]: Error occurred while enabling McInfected v1.5.8 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getById(I)Lorg/bukkit/enchantments/Enchantment;
	at me.bimmr.bimmcore.items.Items.fromString(Items.java:210) ~[?:?]
	at me.bimmr.bimmcore.items.Items.<init>(Items.java:48) ~[?:?]
	at me.bimmr.bimmcore.items.ItemsUtil.getItemStacks(ItemsUtil.java:45) ~[?:?]
	at com.bimmr.mcinfected.Kits.Kit.<init>(Kit.java:69) ~[?:?]
	at com.bimmr.mcinfected.Kits.KitManager.createKit(KitManager.java:33) ~[?:?]
	at com.bimmr.mcinfected.Kits.KitManager.loadKitsFromFile(KitManager.java:119) ~[?:?]
	at com.bimmr.mcinfected.Kits.KitManager.<init>(KitManager.java:23) ~[?:?]
	at com.bimmr.mcinfected.McInfected.reload(McInfected.java:172) ~[?:?]
	at com.bimmr.mcinfected.McInfected.onEnable(McInfected.java:288) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[18:02:07] [Server thread/INFO]: [McInfected] Disabling McInfected v1.5.8
[18:02:07] [Server thread/ERROR]: Error occurred while disabling McInfected v1.5.8 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bimmr.mcinfected.McInfected.onDisable(McInfected.java:202) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```
