### ISSUE TITLE
Typing /mcinfected help doesn't do anything

### ISSUE THREAD

**Issue by JericNisperos** [Bimmr/McInfected#173]
## What's Currently Happening
Everytime I type the /mcinfected help, there are no details showing on the chat. Checked on Console but doesn't have any error messages or any details after I type the command.

----
## Steps to Reproduce (for bugs) / Steps done to fix
1.  Already did reinstalling the plugin. Both MCInfected and Bimmcore. But still doing the same. 
2. Removed other plugins like Citizen2 as it might overlap Bimmcore. Still don't have any error
3. Removing the config files both MCInfected and Bimmcore. Still unable to fix the issue

----
## Error Code
- There are no error codes showing on the console everytime I type the commands. But here is the console details when I type the commands. Already did waiting for several minutes, but still doesn't have any error messages.
```
15:41:38
 issued server command: /mcinfected
15:41:40
 issued server command: /mcinfected help
15:41:44
 issued server command: /mc help
```

----
## Your Environment

* Spigot Version used: 1.12.2
* McInfected Version: 1.6.7
* BimmCore Version:1.0.7
* Any Addons?(Include their versions)
N/A

**Comment by Bimmr** [comment]
Check the log while the server is starting up. If there is no error on the
command then there is an issue while the server is starting up.

**Comment by JericNisperos** [comment]
Thank you. I've checked and found out that it shows:

[BimmCore]: Loading BimmCore v1.0.7
[McInfected]: Loading McInfected v1.6.7

Then after that, it now shows:

[BimmCore]: Enabling BimmCore v1.0.7
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1205]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1205]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1205]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1205]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1205]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1205]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.2.jar:git-Paper-1205]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1205]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[McInfected]: Disabling McInfected v1.6.7

Thank you. And you may DM me on Discord as well: ᴮᴸⁱᵀᶻ #4176

**Comment by Bimmr** [comment]
Are you sure there's no more error? Cause that looks like only half of an
error message.

If that is the full error message then the issue is with the version of
paper spigot you're using not the plugin.
