### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#18]
Hi

A player said to me : "I come down a ladder and i hit the ladder, then i am kick by internal error"

Spigot 1.7.10 and McInfected 1.1.0 (i don't know if the error is fixed in 1.1.1, i'll go to try)

The error : 

[21:12:56 WARN]: Failed to handle packet for /31.34.234.31:57483
net.minecraft.server.v1_7_R4.ReportedException: Ticking player
at net.minecraft.server.v1_7_R4.EntityPlayer.i(EntityPlayer.java:316) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:357) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.PacketPlayInPositionLook.handle(PacketPlayInPositionLook.java:40) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926) ~[?:1.7.0_55]
at java.util.HashMap$KeyIterator.next(HashMap.java:960) ~[?:1.7.0_55]
at net.minecraft.server.v1_7_R4.EntityLiving.aO(EntityLiving.java:453) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.EntityLiving.C(EntityLiving.java:245) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.Entity.h(Entity.java:256) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.EntityLiving.h(EntityLiving.java:1370) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.EntityHuman.h(EntityHuman.java:164) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.EntityPlayer.i(EntityPlayer.java:258) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
... 10 more
[21:12:56 INFO]: Player lost connection: Internal server error

**Comment by Bimmr** [comment]
This looks like a spigot error, so I'd send it to them.
