### ISSUE TITLE
Game not restarting when all players are infected

### ISSUE THREAD

**Issue by Aces52** [Bimmr/McInfected#19]
Title says it all really

**Comment by Aces52** [comment]
It states the humans have survived http://i.imgur.com/JJZvuln.png despite there being no humans left

**Comment by Aces52** [comment]
This stacktrace seems to be the cause:

[20:47:06 ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.1.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:538) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:451) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:570) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.EntityLiving.d(EntityLiving.java:1068) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.EntityHuman.d(EntityHuman.java:860) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:709) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.EntityHuman.damageEntity(EntityHuman.java:801) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.EntityPlayer.damageEntity(EntityPlayer.java:486) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.EntityHuman.attack(EntityHuman.java:1002) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.EntityPlayer.attack(EntityPlayer.java:1051) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1312) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-952179b-2173630]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
        at com.bimmr.mcinfected.IPlayers.IPlayer.win(IPlayer.java:926) ~[?:?]
        at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:139) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-952179b-2173630]
        ... 25 more

**Comment by Bimmr** [comment]
Do you have vault on your server?
Because I've changed a few lines of code in that class, so the line numbers don't match up. But it looks as though you have vault, but no economy plugin. Try removing the cash from the rewards in the config.
