### ISSUE TITLE
Error in log and game can't start

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#21]
Hi

I use 1.1.7b on Spigot 1.7.10

Juste after TP from lobby to arena, a player was kick by server. The virus can't be correctly release and spam, like this : 

http://img11.hostingpics.net/pics/26951120150303194801.png

The game bug after that, there is an error : 

[19:49:25 WARN]: [McInfected] Task #86019 for McInfected v1.1.7b generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
at com.bimmr.mcinfected.IPlayers.IPlayer.infect(IPlayer.java:428) ~[?:?]
at com.bimmr.mcinfected.Lobbys.Timers.chooseAlphas(Timers.java:93) ~[?:?]
at com.bimmr.mcinfected.Lobbys.Timers$4.run(Timers.java:359) ~[?:?]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_55]
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_55]
... 10 more

There is also an error when i use "/inf leave".

**Comment by Bimmr** [comment]
This is something I'm having a hard time fixing as its not catching the
error when I tell it to, can you add me on Skype so I can send a version
which might work.

**Comment by JohOply** [comment]
Sorry i don't use Skype ! I'll try to do it again and i can tell you how i do

Another information : i'm not sure, but i think the player was kick by nocheat because of lag :

[19:47:23 INFO]: [NoCheatPlus] EvoGamer failed SurvivalFly: tried to move from 116.24, 65.02, -114.02 to 115.00, 64.01, -94.00 over a distance of 20.08 block(s). VL 1882.
[19:47:23 INFO]: EvoGamer lost connection: Kicked for flying (or related)
[19:47:23 INFO]: EvoGamer left the game.
[19:47:23 INFO]: [NoCheatPlus] (CONSOLE) Kicked EvoGamer : Kicked for flying (or related)

**Comment by Bimmr** [comment]
The issue is when it tries to show an action bar
