### ISSUE TITLE
[McInfected] Task #84564 for McInfected v1.1.8b generated an exception java.lang.NoSuchMethodError: 

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#25]
Hi

I had this error just after human was infected. I use 1.1.8b & Spigot 1.7.10. The server crashed after that..

[14:54:16 WARN]: [McInfected] Task #84564 for McInfected v1.1.8b generated an exception
java.lang.NoSuchMethodError: me.libraryaddict.disguise.disguisetypes.MobDisguise.getWatcher()Lme/libraryaddict/disguise/disguisetypes/watchers/LivingWatcher;
at com.bimmr.mcinfected.Disguises.LibsDisguises.showName(LibsDisguises.java:66) ~[?:?]
at com.bimmr.mcinfected.Disguises.LibsDisguises.disguise(LibsDisguises.java:37) ~[?:?]
at com.bimmr.mcinfected.Disguises.DisguiseManager.disguise(DisguiseManager.java:59) ~[?:?]
at com.bimmr.mcinfected.IPlayers.IPlayer.disguise(IPlayer.java:180) ~[?:?]
at com.bimmr.mcinfected.IPlayers.IPlayer.infect(IPlayer.java:453) ~[?:?]
at com.bimmr.mcinfected.Lobbys.Timers.chooseAlphas(Timers.java:93) ~[?:?]
at com.bimmr.mcinfected.Lobbys.Timers$4.run(Timers.java:360) ~[?:?]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.2-1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[14:55:21 ERROR]: The server has stopped responding!
[14:55:21 ERROR]: Please report this to http://www.spigotmc.org/
[14:55:21 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[14:55:21 ERROR]: Spigot version: git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)

**Comment by Bimmr** [comment]
Are you using the latest libs disguise?

**Comment by JohOply** [comment]
Sorry for delay, i'm busy !

I use 8.2.6 version of libs disguise !

**Comment by Bimmr** [comment]
Should be working now. Compiling with the latest version of Spigot and LibsDisguise
