### ISSUE TITLE
Something wrong in the McInfected v1.1.9 whit the up-to-date spigot

### ISSUE THREAD

**Issue by shenmadetoufa** [Bimmr/McInfected#29]
[22:07:43] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.1.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:430) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:570) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityLiving.d(EntityLiving.java:1101) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityHuman.d(EntityHuman.java:859) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:742) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityHuman.damageEntity(EntityHuman.java:800) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.Explosion.a(Explosion.java:129) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.createExplosion(World.java:1864) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.WorldServer.createExplosion(WorldServer.java:1010) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityTNTPrimed.explode(EntityTNTPrimed.java:84) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityTNTPrimed.t_(EntityTNTPrimed.java:63) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1605) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.g(World.java:1580) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:584) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NoSuchMethodError: com.shampaggon.crackshot.CSUtility.getWeaponTitle(Lorg/bukkit/entity/TNTPrimed;)Ljava/lang/String;
	at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:90) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	... 25 more
[22:08:00] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.1.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:430) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:570) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityLiving.d(EntityLiving.java:1101) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityHuman.d(EntityHuman.java:859) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:742) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityHuman.damageEntity(EntityHuman.java:800) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.Explosion.a(Explosion.java:129) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.createExplosion(World.java:1864) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.WorldServer.createExplosion(WorldServer.java:1010) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityTNTPrimed.explode(EntityTNTPrimed.java:84) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityTNTPrimed.t_(EntityTNTPrimed.java:63) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1605) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.g(World.java:1580) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:584) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NoSuchMethodError: com.shampaggon.crackshot.CSUtility.getWeaponTitle(Lorg/bukkit/entity/TNTPrimed;)Ljava/lang/String;
	at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:90) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	... 25 more
[22:08:00] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.1.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:430) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:570) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityLiving.d(EntityLiving.java:1101) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityHuman.d(EntityHuman.java:859) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityLiving.damageEntity(EntityLiving.java:742) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityHuman.damageEntity(EntityHuman.java:800) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.Explosion.a(Explosion.java:129) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.createExplosion(World.java:1864) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.WorldServer.createExplosion(WorldServer.java:1010) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityTNTPrimed.explode(EntityTNTPrimed.java:84) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.EntityTNTPrimed.t_(EntityTNTPrimed.java:63) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1605) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.g(World.java:1580) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:584) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NoSuchMethodError: com.shampaggon.crackshot.CSUtility.getWeaponTitle(Lorg/bukkit/entity/TNTPrimed;)Ljava/lang/String;
	at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:90) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3-R0.1-SNAPSHOT.jar:git-Spigot-26dfd01-5cb9b70]
	... 25 more

I think this error is because used the CrackShot Gun with  Grenade (TNT) 
And can you add a new function to set the number of the items in player's  inventroy? 
Now I can't set CrackShot Guns' the number of bullets
Last, this is a real great plugin!

**Comment by Bimmr** [comment]
Ya, this is an issue with crackshot and the grenade. And 'amount:5' would
give 5 of an item

**Comment by shenmadetoufa** [comment]
Thank you
