### ISSUE TITLE
Real death when killed by potion transfer

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#41]
Hi!

I am currently testing your plugin to create nice arenas :)

There is a bug :
1- 3 players joined,
2- 1 player is infected (he has "type:20 duration:10 amplifier:1" - wither- into transfer potion)
3- a second player is infected by killing
4- the third player dead by potion BUT this is a real death (he was teleport to the spawn and there is the real minecraft's death message). The player could use /inf leave to restore his inventory
5- the game is blocked (can't win) and players must to use /inf leave 

And when i use /inf leave in this case, there is errors : http://pastebin.com/Cf5jSTj1

I use Spigot 1.8.7-b534, LibsDisguise 8.6.2 and McInfected 1.2.3

**Comment by Bimmr** [comment]
Are there any errors in the console?

**Comment by JohOply** [comment]
Edited :)

**Comment by Bimmr** [comment]
It's odd that it's the MySQL class that is giving the error... can you enable debug mode and try to get the error to pop up again?

**Comment by JohOply** [comment]
http://pastebin.com/LLLVxpsG

**Comment by Bimmr** [comment]
Gonna message you over Spigot, i need you to get that error to happen with my dev version. I've moved around some code of the MySQL class so the error is pointing me to a blank line now.

**Comment by JohOply** [comment]
I hadn't tested nothing but there is a lots of errors in logs : http://pastebin.com/AYX6Bkqq

**Comment by Bimmr** [comment]
Sent you a version that should fix that.

**Comment by JohOply** [comment]
Tested with new version : http://pastebin.com/XNMaHKHH

**Comment by JohOply** [comment]
[13:11:08 INFO]: Stormclaw190 fell from a high place
[13:11:26 INFO]: Stormclaw190 issued server command: /leave
[13:11:29 INFO]: Stormclaw190 issued server command: /inf leave
[13:11:29 INFO]: Stormclaw190 has left
[13:11:29 INFO]: RICHTSPEED has been infected
[13:11:29 INFO]: RICHTSPEED Equiped with Zombie's Zombie
[13:11:29 INFO]: Stormclaw190 resetting vote
[13:11:29 INFO]: Stormclaw190 has been reset
[13:11:29 INFO]: Stormclaw190 has been healed
[13:11:29 INFO]: Stormclaw190 has been restored

**Comment by JohOply** [comment]
[13:12:59 INFO]: RICHTSPEED walked into fire whilst fighting blackfir
[13:13:30 INFO]: RICHTSPEED issued server command: /inf leave
[13:13:30 INFO]: RICHTSPEED has left
[13:13:30 INFO]: RICHTSPEED resetting vote
[13:13:30 INFO]: RICHTSPEED has 1 total votes
[13:13:30 INFO]: RICHTSPEED has been reset
[13:13:30 INFO]: RICHTSPEED has been healed
[13:13:30 INFO]: RICHTSPEED has been restored
[13:13:30 INFO]: Getting all UUIDs
[13:13:30 INFO]: Updating value into McInfected - 92d22a1f-de6b-37eb-bf77-88a043eadf2a- Time - 485
[13:13:30 INFO]: Getting all UUIDs
[13:13:30 INFO]: Updating value into McInfected - 92d22a1f-de6b-37eb-bf77-88a043eadf2a- Score - 81
[13:13:30 INFO]: Getting all UUIDs
[13:13:30 INFO]: Updating value into McInfected - 92d22a1f-de6b-37eb-bf77-88a043eadf2a- KillStreak - 2
[13:13:30 INFO]: Getting all UUIDs
[13:13:30 INFO]: Updating value into McInfected - 92d22a1f-de6b-37eb-bf77-88a043eadf2a- Kills - 3
[13:13:35 INFO]: blackfir has been reset
[13:13:35 INFO]: blackfir has been healed
[13:13:35 INFO]: Getting all UUIDs
[13:13:35 INFO]: Updating value into McInfected - 69a11693-7835-3933-870b-a40cf1391cc0- Time - 473
[13:13:35 INFO]: Getting all UUIDs
[13:13:35 INFO]: Updating value into McInfected - 69a11693-7835-3933-870b-a40cf1391cc0- Score - 76

**Comment by JohOply** [comment]
Hi !

In latest version, there is the same bug... However, when a survivor die because of fire, he became a zombie

**Comment by Bimmr** [comment]
Try manually adding the potion effect  /effect because when i used that it
worked for me

**Comment by JohOply** [comment]
Okay, i'll try again !

**Comment by JohOply** [comment]
For any reason : (no game started)

[01:10:04 ERROR]: Could not pass event EntityDamageByEntityEvent to McInfected v1.2.4
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:444) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:584) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1101) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:742) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.Explosion.a(Explosion.java:130) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.World.createExplosion(World.java:1866) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.WorldServer.createExplosion(WorldServer.java:1020) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.EntityCreeper.cr(EntityCreeper.java:216) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.EntityCreeper.t_(EntityCreeper.java:103) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]
Caused by: java.lang.NullPointerException
at com.bimmr.mcinfected.Listeners.EntityDamageByEntity.onPlayerDamage(EntityDamageByEntity.java:106) ~[?:?]
at sun.reflect.GeneratedMethodAccessor467.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
... 25 more

**Comment by Bimmr** [comment]
The error points me to a blank line. So i'm not to sure whats happening.

**Comment by Bimmr** [comment]
Was able to test with wither effect on kill, looks like it is fixed. Create another ticket for the other issue please.
