### ISSUE TITLE
Map rotation bug

### ISSUE THREAD

**Issue by JohOply** [Bimmr/McInfected#47]
Hi !

I use 1.2.4 version, Spigot 1.8.7. Often (when we have played on each map, because there is only 2 maps), we can't choose any map and nothing happen at the end of the timer (the sound continues each second, i must reload plugin)

http://i.imgur.com/rB4Swly.png

Error log : 

[16:45:48 WARN]: [McInfected] Task #198567 for McInfected v1.2.4 generated an exception
java.lang.IllegalArgumentException: n must be positive
at java.util.Random.nextInt(Random.java:300) ~[?:1.7.0_55]
at com.bimmr.mcinfected.Lobbys.Timers.getMostVotedArena(Timers.java:99) ~[?:?]
at com.bimmr.mcinfected.Lobbys.Timers.access$5(Timers.java:86) ~[?:?]
at com.bimmr.mcinfected.Lobbys.Timers$5.run(Timers.java:402) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.7-b534.jar:git-Spigot-f94fe8f-2642f9b]
at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]

**Comment by Bimmr** [comment]
This bug is fixed in 1.2.5
