### ISSUE TITLE
Another

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#70]
When i set the MYSQL database on true its this bug in the console and infected ranks not longer work!

[20:06:18 ERROR]: Could not pass event McInfectedLeaveEvent to McInfected-Ranks v1.1.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at com.bimmr.mcinfected.IPlayers.IPlayer.leave(IPlayer.java:513) [McInfected.jar:?]
	at com.bimmr.mcinfected.Command.SubCommands.LeaveCommand.leave(LeaveCommand.java:21) [McInfected.jar:?]
	at com.bimmr.mcinfected.Command.SubCommands.LeaveCommand.execute(LeaveCommand.java:38) [McInfected.jar:?]
	at com.bimmr.mcinfected.Command.CHandler.onCommand(CHandler.java:97) [McInfected.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:242) [server.jar:git-Spigot-db6de12-18fbb24]
	at me.bimmr.mcinfectedlobbyitems.Listeners.onClick(Listeners.java:51) [McInfected-LobbyItems.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_10]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_10]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_10]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_10]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:717) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_10]
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0_10]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_10]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_10]
Caused by: java.lang.NullPointerException
	at com.bimmr.mcinfectedranks.Listeners.PlayerLeave(Listeners.java:150) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_10]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_10]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_10]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_10]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
	... 36 more

**Comment by Bimmr** [comment]
Are you able to enable Debug mode in the config? And then if you get this error again send me the error with the debug messages. I'm not able to get this error when I'm testing it by myself.

**Comment by MacTirom** [comment]
Ok i'm working!

**Comment by MacTirom** [comment]
[20:25:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'inf' in plugin McInfected v1.3.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_10]
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0_10]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_10]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_10]
Caused by: java.lang.NullPointerException
	at com.bimmr.mcinfected.IPlayers.IStats.getKills(IStats.java:93) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:231) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:299) ~[?:?]
	at com.bimmr.mcinfected.Lobbys.IScoreboard.update(IScoreboard.java:275) ~[?:?]
	at com.bimmr.mcinfected.IPlayers.IPlayer.join(IPlayer.java:480) ~[?:?]
	at com.bimmr.mcinfected.Command.SubCommands.JoinCommand.join(JoinCommand.java:64) ~[?:?]
	at com.bimmr.mcinfected.Command.SubCommands.JoinCommand.execute(JoinCommand.java:107) ~[?:?]
	at com.bimmr.mcinfected.Command.CHandler.onCommand(CHandler.java:97) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-db6de12-18fbb24]
	... 16 more
[20:25:58 INFO]: Set Rank Kits

**Comment by MacTirom** [comment]
Oh now

[20:26:47 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- Rank
[20:26:47 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- Exp
[20:26:47 INFO]: CraftPlayer{name=MacTirom} permissions adding -McInfected.Kits.*
[20:26:47 INFO]: CraftPlayer{name=MacTirom} permissions adding McInfected.Kits.Survivor
[20:26:47 INFO]: CraftPlayer{name=MacTirom} permissions adding McInfected.Kits.Zombie
[20:26:47 INFO]: MacTirom has 1 total lives
[20:26:47 INFO]: MacTirom has joined
[20:26:47 INFO]: MacTirom has been healed
[20:26:47 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- Kills
[20:26:47 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- Deaths
[20:26:48 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- Wins
[20:26:48 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- Losses
[20:26:48 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- KillStreak
[20:26:48 INFO]: Getting value from McInfected - 60760e4b-55bc-404d-9409-fa40d796b314- Score
[20:26:48 INFO]: MacTirom has joined a InLobby game state.
[20:26:48 INFO]: Set Rank Kits
[20:26:50 INFO]: MacTirom has opened kits menu for Human
[20:26:50 INFO]: DeinerGeneration issued server command: /inf join
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- Rank
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- Exp
[20:26:50 INFO]: CraftPlayer{name=DeinerGeneration} permissions adding -McInfected.Kits.*
[20:26:50 INFO]: CraftPlayer{name=DeinerGeneration} permissions adding McInfected.Kits.Survivor
[20:26:50 INFO]: CraftPlayer{name=DeinerGeneration} permissions adding McInfected.Kits.Zombie
[20:26:50 INFO]: DeinerGeneration has 1 total lives
[20:26:50 INFO]: DeinerGeneration has joined
[20:26:50 INFO]: DeinerGeneration has been healed
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- Kills
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- Deaths
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- Wins
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- Losses
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- KillStreak
[20:26:50 INFO]: Getting value from McInfected - 7d034bcb-cc62-44b9-99e1-bd93deaf825c- Score
[20:26:50 INFO]: DeinerGeneration has joined a InLobby game state.
[20:26:51 INFO]: Set Rank Kits

**Comment by MacTirom** [comment]
It's working now after a restart don't resett the EXP and the MYSQl work without errors!
Can i disable now the Debug mode or destroy all then? :D

**Comment by Bimmr** [comment]
If you don't mind i would appreciate it if you kept debug mode on, just in case that error appears again.

**Comment by MacTirom** [comment]
i have disable now the debug mode and its working after a restart :+1:

**Comment by MacTirom** [comment]
I commit times the risk :+1:

**Comment by Bimmr** [comment]
No further information about this bug has occurred/been presented.
