### ISSUE TITLE
Mcinfected Glitch

### ISSUE THREAD

**Issue by MERRYACS** [Bimmr/McInfected#73]
![c7bc119525f29df3](https://cloud.githubusercontent.com/assets/17223128/13029615/0bd9a116-d2cc-11e5-9107-aa60291c2476.png)

As you can see we have 3 people, and there is show we have 4. so it wont be stop until the fourth ''person'' gone

**Comment by Bimmr** [comment]
Are there any error messages when the player leaves?

**Comment by MERRYACS** [comment]
Could not pass event PlayerInteractEvent to McInfected v1.3.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:640) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.bimmr.mcinfected.Listeners.FoodHealer$Food
at com.bimmr.mcinfected.Listeners.FoodHealer.playerEat(FoodHealer.java:16) ~[?:?]
at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot-1.7.10-fix.jar:git-PaperSpigot-88857d9]
... 15 more

**Comment by Bimmr** [comment]
Don't use /reload. And if you didn't then reupload the plugin's jar to the server because when you uploaded it must have gotten corrupted.

**Comment by Bimmr** [comment]
Is the player leaving by using a command or by logging out?

**Comment by MERRYACS** [comment]
they leave without any command.

**Comment by Bimmr** [comment]
So do they just log off?

**Comment by MERRYACS** [comment]
yes

**Comment by Bimmr** [comment]
Not able to replicate this bug with the latest version of McInfected
