### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected#78]
```
Caused by: java.lang.NegativeArraySizeException
at com.bimmr.mcinfected.Utils.StringUtil.combineArgs(StringUtil.java:86) ~[?:?]
at com.bimmr.mcinfectedranks.Commands.AdminCommand.rank(AdminCommand.java:109) ~[?:?]
at com.bimmr.mcinfectedranks.Commands.AdminCommand.execute(AdminCommand.java:100) ~[?:?]
at com.bimmr.mcinfected.Command.CHandler.onCommand(CHandler.java:97) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
... 15 more
```
Caused because you didn't have a zombies tag in your Ranks.yml

**Comment by Bimmr** [comment]
Can you send me your Ranks.yml?

**Comment by MacTirom** [comment]
# Ranks do NOT require kits, or pemissions to work, It's Just an optional feature, you can remove them if you wish.
# Make sure to look at the Github Wiki if you have any questions!
# If you have -1 as the exp, the rank will not go up.
# Prefixes can only be a maximum of 16 characters!
# You DO need a permissions plugin for the permissions to be added/removed to/from. This plugin does not handle the permissions
Ranks:
  Recruit:
    Prefix: '&6[&fRecruit&6]'
    Default: true
    Next Rank: Private
    Exp: 300
    Default Kit:
      Human: RecruitK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.RecruitK
    - McInfected.Kits.Zombie
  Private:
    Prefix: '&6[&7Private&6]'
    Exp: 600
    Next Rank: Corporal
    Default Kit:
      Human: PrivateK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.PrivateK
    - McInfected.Kits.Zombie
  Corporal:
    Prefix: '&6[&8Corporal&6]'
    Exp: 900
    Next Rank: Sergeant
    Default Kit:
      Human: CorporalK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.CorporalK
    - McInfected.Kits.Zombie
  Sergeant:
    Prefix: '&6[&eSergeant&6]'
    Exp: 1200
    Next Rank: SSergeant
    Default Kit:
      Human: SergeantK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.SergeantK
    - McInfected.Kits.Zombie
  SSergeant:
    Prefix: '&6[&dS.Serg_&6]'
    Exp: 1500
    Next Rank: FSergeant
    Default Kit:
      Human: SSergK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.SSergK
    - McInfected.Kits.Zombie
  FSergeant:
    Prefix: '&6[&5F.Serg_&6]'
    Exp: 1800
    Next Rank: SMajor
    Default Kit:
      Human: FSergK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.FSergK
    - McInfected.Kits.Zombie
  SMajor:
    Prefix: '&6[&aS.Major&6]'
    Exp: 2100
    Next Rank: Captain
    Default Kit:
      Human: SMajorK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.SMajorK
    - McInfected.Kits.Zombie
  Captain:
    Prefix: '&6[&2Captain&6]'
    Exp: 2400
    Next Rank: Major
    Default Kit:
      Human: CaptainK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.CaptainK
    - McInfected.Kits.Zombie
  Major:
    Prefix: '&6[&bMajor&6]'
    Exp: 2700
    Next Rank: Colonel
    Default Kit:
      Human: MajorK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.MajorK
    - McInfected.Kits.Zombie
  Colonel:
    Prefix: '&6[&3Colonel&6]'
    Exp: 3000
    Next Rank: MGeneral
    Default Kit:
      Human: ColonelK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.ColonelK
    - McInfected.Kits.Zombie
  MGeneral:
    Prefix: '&6[&9MGeneral&6]'
    Exp: 3300
    Next Rank: General
    Default Kit:
      Human: MGeneralK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.MGeneralK
    - McInfected.Kits.Zombie
  General:
    Prefix: '&6[&cGeneral&6]'
    Exp: 3600
    Next Rank: Chief
    Default Kit:
      Human: GeneralK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.GeneralK
    - McInfected.Kits.Zombie
  Chief:
    Prefix: '&6[&4Chief&6]'
    Exp: 3900
    Default Kit:
      Human: ChiefK
      Infected: Zombie
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.ChiefK
    - McInfected.Kits.Zombie
  Infecter:
    Prefix: '&7[&1Infecter&7]&n'
    Exp: -1
    Permissions:
    - -McInfected.Kits.*
    - McInfected.Kits.Infecter
    - McInfected.Kits.Zombie

**Comment by MacTirom** [comment]
Here is a new error Log:



[09:01:02 ERROR]: Could not pass event InventoryClickEvent to McInfected v1.3.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
at com.bimmr.mcinfected.Command.SubCommands.KitCommand.setKit(KitCommand.java:27) ~[?:?]
at com.bimmr.mcinfected.MenuManager$2.onOptionClick(MenuManager.java:134) ~[?:?]
at com.bimmr.mcinfected.Utils.IconMenu.onInventoryClick(IconMenu.java:123) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
... 15 more

**Comment by MacTirom** [comment]
New bad Errror Log :/

[22:46:26 ERROR]: Could not pass event InventoryClickEvent to McInfected v1.3.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
at com.bimmr.mcinfected.MenuManager$4.onOptionClick(MenuManager.java:306) ~[?:?]
at com.bimmr.mcinfected.Utils.IconMenu.onInventoryClick(IconMenu.java:123) ~[?:?]
at sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
... 15 more

**Comment by Bimmr** [comment]
Quick question: Do you ever use /reload ?

**Comment by Bimmr** [comment]
For the first error you posted, you have no Zombie kits in your kits.yml (You're missing the Zombie tag)

**Comment by Bimmr** [comment]
These should be fixed when i upload the new version
